# Generated by Django 2.2.12 on 2022-05-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_auto_20220504_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[['male', 'Мужской'], ['female', 'Женский'], ['unknown', 'Вертолет']], default='male', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.CharField(choices=[['none', 'Не определенно'], ['single', 'Холост'], ['in_a_rel', 'В отношениях'], ['engaged', 'Помолвлен(а)'], ['married', 'Женат/Замужем'], ['in_love', 'Влюблен(а)'], ['complicated', 'Все сложно'], ['cool', 'Ем пельмешки'], ['2D', 'Влюблена в 2D']], default='none', max_length=20, verbose_name='Статус отношений'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
